module.exports = {
  darkMode: "class",
  content: [
    "./content/**/*.md",
    "./layouts/**/*.html",
    "./assets/js/*.js",
  ],
  theme: {
    fontSize: {
      "h3": "1.25em",
    },
    extend: {
      colors: {
        "search-bar-border-light": "#CCCCCC",
        "search-bar-border-dark": "#333333",
        "admonition-note-light": "#448aff",
        "admonition-note-dark": "rgba(68, 138, 255, 0.1)",
        "admonition-abstract-light": "#00b0ff",
        "admonition-abstract-dark": "rgba(0, 176, 255, 0.1)",
        "admonition-info-light": "#00b8d4",
        "admonition-info-dark": "rgba(83, 211, 230, 0.1)",
        "admonition-tip-light": "#00bfa5",
        "admonition-tip-dark": "rgba(0, 191, 165, 0.1)",
        "admonition-success-light": "#00c853",
        "admonition-success-dark": "rgba(0, 200, 83, 0.1)",
        "admonition-question-light": "#64dd17",
        "admonition-question-dark": "rgba(100, 221, 23, 0.1)",
        "admonition-warning-light": "#ff9100",
        "admonition-warning-dark": "rgba(255, 145, 0, 0.1)",
        "admonition-failure-light": "#ff5252",
        "admonition-failure-dark": "rgba(255, 82, 82, 0.1)",
        "admonition-danger-light": "#ff1744",
        "admonition-danger-dark": "rgba(68, 138, 255, 0.1)",
        "admonition-bug-light": "#f50057",
        "admonition-bug-dark": "rgba(255, 23, 68, 0.1)",
        "admonition-example-light": "#651fff",
        "admonition-example-dark": "rgba(101, 31, 255, 0.1)",
        "admonition-quote-light": "#9e9e9e",
        "admonition-quote-dark": "rgba(159, 159, 159, 0.1)",
      },
      typography: (theme) => ({
        singularisart: {
          css: {
            "--tw-prose-body": theme("colors.gray[700]"),
            "--tw-prose-headings": theme("colors.gray[900]"),
            "--tw-prose-lead": theme("colors.gray[600]"),
            "--tw-prose-links": theme("colors.sky[600]"),
            "--tw-prose-bold": theme("colors.gray[900]"),
            "--tw-prose-counters": theme("colors.gray[500]"),
            "--tw-prose-bullets": theme("colors.gray[400]"),
            "--tw-prose-hr": theme("colors.gray[200]"),
            "--tw-prose-quotes": theme("colors.gray[900]"),
            "--tw-prose-quote-borders": theme("colors.gray[200]"),
            "--tw-prose-captions": theme("colors.gray[500]"),
            "--tw-prose-code": theme("colors.gray[900]"),
            "--tw-prose-pre-code": theme("colors.gray[200]"),
            "--tw-prose-pre-bg": theme("colors.gray[800]"),
            "--tw-prose-th-borders": theme("colors.gray[300]"),
            "--tw-prose-td-borders": theme("colors.gray[200]"),

            "--tw-prose-invert-body": theme("colors.gray[300]"),
            "--tw-prose-invert-headings": theme("colors.neutral[200]"),
            "--tw-prose-invert-lead": theme("colors.gray[400]"),
            "--tw-prose-invert-links": theme("colors.sky[500]"),
            "--tw-prose-invert-bold": theme("colors.neutral[300]"),
            "--tw-prose-invert-counters": theme("colors.gray[400]"),
            "--tw-prose-invert-bullets": theme("colors.gray[400]"),
            "--tw-prose-invert-hr": theme("colors.gray[700]"),
            "--tw-prose-invert-quotes": theme("colors.gray[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.gray[700]"),
            "--tw-prose-invert-captions": theme("colors.gray[400]"),
            "--tw-prose-invert-code": theme("colors.neutral[300]"),
            "--tw-prose-invert-pre-code": theme("colors.gray[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.gray[600]"),
            "--tw-prose-invert-td-borders": theme("colors.gray[700]"),

            "--correct": "#00FF00",
            "--incorrect": "#FF0000",
            "--solution": "#00AEEF",
            "--qedsolution": "#76B4CF",
            "--proof": "#F035A3",
            "--definition": "#F035A3",
            "--theorem": "#F035A3",
            "--lemma": "#F035A3",
            "--remark": "#F035A3",
            "--qedproof": "#F035A3",
            "--question": "#00A6E4",
            "--questionfg": "#F2FBF8",
            "--example": "#00A6E4",
            "--examplebg": "#F2FBF8",

            h1: {
              fontSize: "2.25rem",
              lineHeight: "2.5rem",
              marginBottom: "2rem",
              fontWeight: "600",
            },
            h2: {
              fontWeight: "550",
              fontSize: "1.5em",
              marginTop: "1em",
              marginBottom: "1em",
              lineHeight: "1.33",
            },
            h3: {
              fontWeight: "550",
              fontSize: "1.25em",
              marginTop: "1.6em",
              marginBottom: "0.6em",
              lineHeight: "1.6",
            },
            h4: {
              fontWeight: "550",
              marginTop: "1.5em",
              marginBottom: "0.5em",
              lineHeight: "1.5",
            },
            img: {
              marginTop: "0.5rem",
              marginBottom: "0.5rem",
            },
            code: {
              fontWeight: "normal",
            },
            "code::before": {
              content: "none",
            },
            "code::after": {
              content: "none",
            },
            a: {
              fontWeight: "normal",
              color: "var(--tw-prose-links)",
              "&:hover": {
                textDecoration: "underline",
              },
            },
          },
        },
      }),
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
  ],
};
